[project]
name = "wordpresscommentwatcher"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "aiohttp~=3.11.13",
    "discord-py~=2.5.0",
    "markdown2>=2.5.3",
    "markdownify>=1.1.0",
    "requests>=2.32.3",
]
